### ISSUE TITLE
Screenshot Request

### ISSUE THREAD

**Issue by ElectricPrism** [bbidulock/gchooser#1]
Add a screenshot of what it looks like please.

**Comment by bbidulock** [comment]
![shot](https://cloud.githubusercontent.com/assets/5490751/20520983/45e9beae-b066-11e6-98a5-fca0e1393b1b.jpg)

You might want to use xde-xchooser from the [xde-session](/bbidulock/xde-session) repository.  It can look the same (as below), but is much more highly configurable.  It is written in C and can also log in directly (by looping back to localhost).

![tmp](https://cloud.githubusercontent.com/assets/5490751/20521565/091af7c4-b069-11e6-9862-87c07cfc4b88.jpg)
